### ISSUE TITLE
Week 01 - Day 4 - Mock Portoflio

### ISSUE THREAD

**Issue by mdewey** [aperniciaro/assignments#4]
# A Portfolio

For your first weekend project, we're going to be starting work on a portfolio website that you can improve over the rest of your career.

![Mockup](https://raw.githubusercontent.com/tiy-tpa-fee/assignments/master/portfolio/mockup.png)

You can find image assets you'll need here:

> https://github.com/tiy-tpa-fee/assignments/tree/master/portfolio/assets

The font used is [Roboto](https://fonts.google.com/specimen/Roboto).

Also, feel free to change it from Jason's picture to a picture of yourself.

## Objectives

- Build on your knowledge of HTML & CSS
- Implement, from scratch, a given design
- Use flexbox techniques layout pages.

## Requirements

- Initially, you should implement the design as close as possible to the mockup. Later, you might choose to fit your personality/style.

- **Note**: You should complete at least the tasks given for _explorer_ mode as listed below before turning in the assignment, as well as before attempting _adventure_ or _epic_ modes.

### Explorer Mode

- [ ] Recreate the page as closely as you possibly can. Use the same fonts, sizes, and colors.
- [ ] Make sure the site is responsive.
- [ ] Deploy your site

### Adventure Mode

- [ ] Take the time to personalize the site with information about yourself, links to your projects, and your pictures.
- [ ] Keep it professional, but make it your own.

### Epic Mode
- [ ] Go back and work on the adventure or epic mode for a past assignment.
- [ ] Start to research [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript)

**Comment by aperniciaro** [comment]
https://github.com/aperniciaro/portfolio.git
Explorer mode
Could not get the triangle on the speech bubble.

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBYZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--337d5db9d88e083c06c448999f852548342972b5/giphy-18.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/83)**__

**Comment by mdewey** [comment]
So I have to ask, why do you have some many html files?

**Comment by aperniciaro** [comment]
I was intending to add files to link from the sliced project icons and blog excerpts; the additional html files would have been pages with each of the full images/blog posts. But then I looked at the clock and decided not to build those out at this time.
