### ISSUE TITLE
Week 02 - Day 2 - Scoreboard, part 2

### ISSUE THREAD

**Issue by mdewey** [aperniciaro/assignments#6]
# Score Board, Part 2

For this assignment, you will be extending and giving your scoreboard some features.

## Requirements

- use last night's project, add a max score, a min score, and a winner.

### Explorer Mode

- [ ] Add an `if` statement to stop each team's score from going below 0.
- [ ] Add an `if` statement to stop each team's score from going above 21
- [ ] When a team gets 21 points, disable the buttons and display a message to the user of who won
- [ ] Add a `reset` button that resets the scoreboard back to each team having 0 points and re-enables the buttons

### Adventure Mode

- [ ] Add more CSS to the winning teams score to indicate who won.
- [ ] Implement a Quarter/Period Tracker that would be appropriate for the sport.
- [ ] Add some styling to make it more presentable. Have fun with it.
- [ ] Make the layout responsive.

### Epic Mode

- [ ] Add a Timer that counts down automatically and updates the period/quarter appropriately.
- [ ] Save/load the information to local storage.
- [ ] Add anything else that your sport would have on its scoreboard (e.g., fouls, sacks, shots on goal, etc.).
- [ ] Improve the UX to help to make scorekeeping by your sport easier.

### Super Epic mode

- [ ] Start working on creating a two-player Tic Tac Toe.

### Resources

Today's slides: https://slides.com/markdewey-1/if-else/#/

**Comment by aperniciaro** [comment]
https://github.com/aperniciaro/scoreboard.git
Explorer mode done. Continuing to Adventure

**Comment by aperniciaro** [comment]
Added styling to winning score and period tracker, per Adventure

**Comment by mdewey** [comment]
Your homework was marked: **Exceeds Expectations**

![Niiiiiiiiice!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0f7e0d5535291cc82f410da4761392ed248ba5a6/tumblr_inline_odd2x9PvYg1raprkq_400.gif)
> &ldquo;Niiiiiiiiice!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/65)**__
