### ISSUE TITLE
Week 03 - day 1 - Catch your Breath

### ISSUE THREAD

**Issue by mdewey** [aperniciaro/assignments#9]
# Catch your Breath

We have been going at a fast pace for the past couple of weeks. Every so often, you need to reflect on how far you have come.

In this assignment, we are going to take a little _code_ break and create a blog post. Writing is a good way to reflect on what you have done and also share some knowledge. The best way to get better at talking about technology is practice. Blog posts are a way to practice that skill.

## Objectives

- Practice talking about technology
- Reinforce a topic we have covered in class

## Requirements

- Create a blog on [Medium](https://medium.com/).

### Explorer Mode

- [ ] On [Medium](https://medium.com/), create a blog post that talks about a concept we have gone over in class. This could anything topic from HTML, CSS or JavaScript, or a "lesson learned" from the past couple of weeks. As a challenge, consider picking a topic you think you are weak on. Remember, you are creating a developer-focused blog post.
- [ ] Solve this kata: [https://www.codewars.com/kata/volume-of-a-cuboid](https://www.codewars.com/kata/volume-of-a-cuboid) To turn this in, create a [gist](https://gist.github.com) of your code and submit a link to it.
- [ ] Submit the link to your published blog post when turning in this assignment.

## Adventure Mode

- [ ] continue to work on blackjack
- [ ] As we progress, we will be using different tools to work our brain. Today, head over to [HackerRank](https://www.hackerrank.com/). This is another tool, like [Codewars](https://www.codewars.com/) to practice our developer skills. As a start, head into the algorithms section, and try [Grading Students](https://www.hackerrank.com/challenges/grading/problem).
- [ ] To turn this in, create a [gist](https://gist.github.com) of your code and submit a link to it.

### Epic Mode

- [ ] Go back and finish up any outstanding work.
- [ ] Go back to a previous assignment and work on it some more. This could be trying to tackle a harder level, working on the UI/UX, refactoring the code to a new idea that we covered (e.g. functions and abstractions), or adding unit tests.
- [ ] To turn this in, link to the other project's repository, and describe what you did.

**Comment by aperniciaro** [comment]
https://gist.github.com/aperniciaro/20b22a0d8136a65b1e9861c2996236a3

**Comment by aperniciaro** [comment]
https://medium.com/@andrew.perniciaro/writing-css-when-my-shirt-doesnt-match-my-pants-9f7be5588b56

**Comment by aperniciaro** [comment]
https://github.com/aperniciaro/blackjack
fixed my initial blackjack program, but does not include new concepts from today's class

**Comment by aperniciaro** [comment]
https://gist.github.com/aperniciaro/bb815afae92d44e497f741f56fce0346

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Great job!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBJdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8167037ff2098b5e812290b56d35e1113c17439d/giphy-downsized.gif)
> &ldquo;Great job!&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/24)**__
